version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dbdemo-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-YourStrong@Passw0rd}
      - MSSQL_PID=Developer
    ports:
      - "1453:1433"
    volumes:
      # Persist database files
      - sqlserver-data:/var/opt/mssql
      # Optional: Add initialization scripts
      - ./scripts/init:/docker-entrypoint-initdb.d
    networks:
      - dbdemo-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${SA_PASSWORD:-YourStrong@Passw0rd}" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqlserver-data:
    driver: local

networks:
  dbdemo-network:
    driver: bridge
