using System.Text;

namespace DbDemo.Scaffolding;

public class CodeGenerator
{
    public string GenerateTablesClass(List<TableSchema> tables)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file is automatically generated by the DbDemo.Scaffolding tool.");
        sb.AppendLine("// Do not edit this file manually - your changes will be overwritten.");
        sb.AppendLine("// Regenerate by running: dotnet run --project src/DbDemo.Scaffolding");
        sb.AppendLine();
        sb.AppendLine("namespace DbDemo.Infrastructure.SqlKata.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Contains constants for all table names in the database schema.");
        sb.AppendLine("/// Use these constants instead of magic strings to get compile-time checking.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Tables");
        sb.AppendLine("{");

        foreach (var table in tables.OrderBy(t => t.TableName))
        {
            sb.AppendLine($"    /// <summary>Table: {table.TableName}</summary>");
            sb.AppendLine($"    public const string {table.TableName} = \"{table.TableName}\";");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    public string GenerateColumnsClass(List<TableSchema> tables)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file is automatically generated by the DbDemo.Scaffolding tool.");
        sb.AppendLine("// Do not edit this file manually - your changes will be overwritten.");
        sb.AppendLine("// Regenerate by running: dotnet run --project src/DbDemo.Scaffolding");
        sb.AppendLine();
        sb.AppendLine("namespace DbDemo.Infrastructure.SqlKata.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Contains constants for all column names in the database schema, organized by table.");
        sb.AppendLine("/// Use these constants instead of magic strings to get compile-time checking.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Columns");
        sb.AppendLine("{");

        foreach (var table in tables.OrderBy(t => t.TableName))
        {
            sb.AppendLine($"    /// <summary>Columns for {table.TableName} table</summary>");
            sb.AppendLine($"    public static class {table.TableName}");
            sb.AppendLine("    {");

            foreach (var column in table.Columns.OrderBy(c => c.ColumnName))
            {
                var nullableInfo = column.IsNullable ? " (nullable)" : " (not null)";
                var typeInfo = column.MaxLength.HasValue
                    ? $"{column.DataType}({column.MaxLength})"
                    : column.DataType;

                sb.AppendLine($"        /// <summary>{typeInfo}{nullableInfo}</summary>");
                sb.AppendLine($"        public const string {column.ColumnName} = \"{column.ColumnName}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    public async Task WriteGeneratedFilesAsync(
        string outputDirectory,
        List<TableSchema> tables,
        CancellationToken cancellationToken = default)
    {
        // Ensure output directory exists
        Directory.CreateDirectory(outputDirectory);

        // Generate and write Tables.cs
        var tablesCode = GenerateTablesClass(tables);
        var tablesFilePath = Path.Combine(outputDirectory, "Tables.cs");
        await File.WriteAllTextAsync(tablesFilePath, tablesCode, cancellationToken);

        // Generate and write Columns.cs
        var columnsCode = GenerateColumnsClass(tables);
        var columnsFilePath = Path.Combine(outputDirectory, "Columns.cs");
        await File.WriteAllTextAsync(columnsFilePath, columnsCode, cancellationToken);

        Console.WriteLine($"✓ Generated {tablesFilePath}");
        Console.WriteLine($"✓ Generated {columnsFilePath}");
    }
}
